### GET ALL PRODUCTS
GET http://localhost:3000/api/v1/products

### CREATE A PRODUCT (Copy this for Postman)
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "title": "Classic White Sweatshirt EX",
  "price": 55,
  "description": "Elevate your casual wardrobe with our Classic White Sweatshirt.",
  "category": "REPLACEME_WITH_CATEGORY_ID", 
  "images": [
    "https://i.imgur.com/cSytoSD.jpeg"
  ]
}

### UPDATE A PRODUCT
PUT http://localhost:3000/api/v1/products/REPLACEME_WITH_PRODUCT_ID
Content-Type: application/json

{
  "price": 60,
  "title": "Classic White Sweatshirt EX Updated"
}

### SOFT DELETE A PRODUCT
DELETE http://localhost:3000/api/v1/products/REPLACEME_WITH_PRODUCT_ID

### GET ALL CATEGORIES (To get Category ID)
GET http://localhost:3000/api/v1/categories
